version: '3'

networks:
  loki:

services:
  rsyslog:
    build: ./rsyslogd
    ports:
      - '514:514/udp'
    cap_add:
      - SYSLOG
    networks:
      - loki
  loki:
    image: grafana/loki:2.8.11
    ports:
      - '3100:3100'
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.8.11
    ports:
      - '1514:1514'
      - '9080:9080'
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yaml
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yaml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    networks:
      - loki
